# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IlegraChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IlegraChallenge
	#Network
    pod 'Alamofire'#, '~> 4.7'
    pod 'AlamofireObjectMapper'#, '~> 5.0'
    pod 'AlamofireImage', '~> 3.4'

  target 'IlegraChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
